spring:
  boot:
    message: 'Load from Config Server: Hello from department service'
  datasource:
    url: jdbc:h2:file:./data/department-service/department-db;AUTO_SERVER=true
    username: root
    password: pass
    driver-class-name: org.h2.Driver
  jpa:
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
        hbm2ddl:
          auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
