spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/mydb'
    username: root
    password: pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update
  output:
    ansi:
      enabled: always
  boot:
    message: 'Hello, Department Service. Testing the config server'

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

