spring:
  boot:
    message: 'Update message using Spring Cloud Bus (busrefresh)!'
  datasource:
    url: jdbc:h2:file:./data/department-service/department-db;AUTO_SERVER=true
    username: root
    password: pass
    driver-class-name: org.h2.Driver
  jpa:
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
        hbm2ddl:
          auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    

springdoc:
  swagger-ui:
    use-root-path: true
#    default-models-expand-depth: -1
  version: '@springdoc-openapi-starter-webmvc-ui.version@'


management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1

      
logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'
