spring:
  boot:
    message: 'Load from Config Server: Message of Employee Service using Spring Cloud Bus'
  datasource:
    url: jdbc:h2:file:./data/employee-service/employee-db;AUTO_SERVER=true
    username: root
    password: pass
    driver-class-name: org.h2.Driver
  jpa:
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
        hbm2ddl:
          auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    

      
logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'
